import type { ReportItem } from "@/types/reports";

export const MOCSReports: ReportItem[] = [
  {
    id: 1,
    date: "2025-01-11",
    transactionAmount: 45,
    transactionType: "Purchase",
    userId: 23,
    productName: "Laptop",
    quantity: 1,
  },
  {
    id: 2,
    date: "2024-12-15",
    transactionAmount: 23,
    transactionType: "Refund",
    userId: 45,
    productName: "Phone",
    quantity: 2,
  },
  {
    id: 3,
    date: "2025-02-10",
    transactionAmount: 67,
    transactionType: "Purchase",
    userId: 12,
    productName: "Headphones",
    quantity: 1,
  },
  {
    id: 4,
    date: "2024-11-25",
    transactionAmount: 88,
    transactionType: "Purchase",
    userId: 56,
    productName: "Monitor",
    quantity: 2,
  },
  {
    id: 5,
    date: "2024-05-05",
    transactionAmount: 34,
    transactionType: "Refund",
    userId: 78,
    productName: "Keyboard",
    quantity: 1,
  },
  {
    id: 6,
    date: "2024-06-12",
    transactionAmount: 56,
    transactionType: "Purchase",
    userId: 39,
    productName: "Mouse",
    quantity: 3,
  },
  {
    id: 7,
    date: "2024-07-17",
    transactionAmount: 90,
    transactionType: "Purchase",
    userId: 12,
    productName: "Smartwatch",
    quantity: 1,
  },
];
